# Generated by Django 4.0.3 on 2022-04-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[(1, 'Admin'), (2, 'Customer'), (3, 'Company')], default=1, max_length=20),
        ),
    ]
