# Generated by Django 4.0.3 on 2022-04-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[(1, 'Admin'), (2, 'Customer'), (3, 'Company')], default=2, max_length=20),
        ),
    ]
