# Generated by Django 4.0.3 on 2022-04-07 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='accepted',
            new_name='order',
        ),
    ]
