# Generated by Django 4.0.3 on 2022-04-07 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_accepted_product_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptbid',
            name='author',
        ),
    ]
