# Generated by Django 4.0.2 on 2022-04-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_acceptbid_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='accepted_bid',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AcceptBid',
        ),
    ]
