# Generated by Django 4.0.2 on 2022-04-09 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_bid_accepted_bid_delete_acceptbid'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delv_date', models.DateField()),
                ('delv_partner', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('payment', models.CharField(max_length=255)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bid')),
            ],
        ),
    ]
