# Generated by Django 4.0.2 on 2022-04-09 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='delivery_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delv_date',
            new_name='delivery_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delv_partner',
            new_name='payment_status',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='location',
            new_name='product_location',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payment',
            new_name='shipping_partner',
        ),
    ]
